---
framework: mocha

preRun:
     command:
        - apt update -y
        - apt install build-essential -y
        - curl https://sh.rustup.rs -sSf | bash -s -- -y
        - source $HOME/.cargo/env
        - rustup --version
        - cargo --version
        - yarn
        - yarn build-native
preMerge:
  pattern:
    - "packages/*/!(integration-tests|fs-write-stream-atomic)/test/*.js"

postMerge:
  pattern: 
    - "packages/*/!(integration-tests|fs-write-stream-atomic)/test/*.js"

configFile: ".mocharc.json"

version: 1.0
